name: Build Docker images

on:
  workflow_dispatch:   # solo manual para no molestar

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend
        run: docker build -t doc-copilot-backend -f backend/Dockerfile .

      - name: Build frontend
        run: docker build -t doc-copilot-frontend -f frontend/Dockerfile .
